### ISSUE TITLE
Change brightness with pot mapped values

### ISSUE THREAD

**Issue by sdparkes66** [AKJ7/TM1637#11] opened 2021-09-04 09:47 UTC
When using the below the brightness value changes, however, the display just goes off..

Would be handy to be able to change the display brightness using a pot :)

```
void loop()
{
int sensorValue = analogRead(A0);
int brightness = map(sensorValue, 0, 1023, 0, 7);
tm1637.setBrightness(brightness);
Serial.println(brightness);
tm1637.display(4444)->blink(1000);
}

```

**Comment by AKJ7** [comment] 2021-09-04 10:12
> Would be handy to be able to change the display brightness using a pot :)

Pot? Potentiometer?
It IS possible to change the display brightness using a potentiometer. 
Can you tell me what  `Serial.println(brightness);` prints?
Can you also show me the whole code?

(I suspect it has to do with how i implemented the `blink()` function. The last display brightness is statically saved! Later i realised that i didn't need the static value).
Could you check what would happen if you did the following instead?
```c++
void loop()
{
    int sensorValue = analogRead(A0);
    int brightness = map(sensorValue, 0, 1023, 0, 7);
    tm1637.setBrightness(brightness);
    tm1637.display(brightness);
}
```

**Comment by sdparkes66** [comment] 2021-09-11 14:31
Hi, thanks for the reply, tried that and made no difference, the map worked and the value changed as expected between 0-7

**Comment by AKJ7** [comment] 2021-09-11 22:01
> Hi, thanks for the reply, tried that and made no difference, the map worked and the value changed as expected between 0-7

Do you mean the value displayed on the display are expected but not the brightness?
Then this is really strange. I will test it myself when i will have time.

**Comment by AKJ7** [comment] 2023-12-26 19:59
Hey man, just tested on real hardware, but couldn't reproduce the error. I am going to assume it has to do with your hardware setup. Closing this ticket. Reopen it in case you can reproduce the error.

**Closed by AKJ7** 2023-12-26 19:59 UTC

**Comment by AKJ7** [comment] 2023-12-26 20:03
This is the code i used:
```cpp
#include <TM1637.h>


// Instantiation and pins configurations
// Pin 3 - > DIO
// Pin 2 - > CLK
TM1637 tm(2, 3);

void setup()
{
    tm.begin();
    Serial.begin(9600);
}

void loop()
{
    int sensorValue = random(0, 1023);
    int brightness = map(sensorValue, 0, 1023, 0, 7);
    tm.setBrightness(brightness);
    Serial.println(brightness);
    tm.clearScreen();
    tm.display(sensorValue)->blink(1000);
    delay(1000);
}
```
